name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'pull_request' }}
    steps:
      - uses: actions/checkout@v2
        name: Checkout [master]
        with:
          fetch-depth: 0
      - name: Derive SHAs for base and head flags in `nx affected` commands
        uses: nrwl/nx-set-shas@v2
        with:
          main-branch-name: master
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
      - run: npm install
      - name: Build
        run: npx nx affected --target build --with-deps --parallel --max-parallel=3
      - name: Publish
        run: npx nx affected --target publish --parallel --max-parallel=2
  pr:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0
      - name: Derive SHAs for base and head flags in `nx affected` commands
        uses: nrwl/nx-set-shas@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
      - run: npm install
      - name: Build
        run: npx nx affected --target build --with-deps --parallel --max-parallel=3
      - name: Publish
        run: npx nx affected --target publish --parallel --max-parallel=2
